USE testdb;
show tables;
describe storages;
select * from storages;
describe products;
select * from products;
describe storage_product;
select * from storage_product;
describe lists;
select * from lists;
describe list_product;
select * from list_product;
